# Generated by Django 3.1.3 on 2020-12-16 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackloggedGamesModel',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(default='', max_length=1024)),
                ('cover_url', models.URLField(default='')),
                ('platform_id', models.IntegerField()),
                ('platform_name', models.CharField(default='', max_length=1024)),
                ('status_id', models.IntegerField(default=0)),
                ('status_name', models.CharField(max_length=1024)),
                ('date_added', models.DateField(default='1970-01-01')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
