# Generated by Django 3.1.4 on 2021-01-02 00:12

import backlogger.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackloggedGamesModel',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=1024)),
                ('game_name', models.CharField(max_length=1024)),
                ('cover_url', models.URLField()),
                ('platform_id', models.IntegerField()),
                ('platform_name', models.CharField(max_length=1024)),
                ('status_id', models.IntegerField(default=0)),
                ('status_name', models.CharField(max_length=1024)),
                ('date_added', models.DateField()),
                ('is_custom', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTimezoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGame',
            fields=[
                ('backlogged', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.backloggedgamesmodel')),
                ('involved_companies', models.CharField(default=None, max_length=1024)),
                ('summary', models.CharField(default=None, max_length=1024)),
                ('cover_img', models.ImageField(storage=backlogger.storage.OverwriteStorage(), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
