# Generated by Django 3.1.4 on 2021-01-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgame',
            name='summary',
            field=models.CharField(default=None, max_length=3000),
        ),
    ]
