# Generated by Django 3.1.3 on 2020-12-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggedgamesmodel',
            name='date_added',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
