# Generated by Django 3.1.3 on 2020-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201216_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggedgamesmodel',
            name='date_added',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
