# Generated by Django 3.1.4 on 2021-01-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210101_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgame',
            name='cover_img',
            field=models.ImageField(upload_to='Backlogged Custom Games/'),
        ),
    ]
