# Generated by Django 3.1.4 on 2020-12-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201230_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgamemodel',
            old_name='custom_game',
            new_name='backlog_entry',
        ),
    ]
