# Generated by Django 3.1.4 on 2020-12-19 02:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20201217_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackloggedGameModel',
            new_name='BackloggedGamesModel',
        ),
    ]
