# Generated by Django 3.1.4 on 2020-12-30 18:22

import backlogger.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20201230_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGameModel',
            fields=[
                ('backlog_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='custom_game', serialize=False, to='app.backloggedgamesmodel')),
                ('involved_companies', models.CharField(default='', max_length=1024)),
                ('summary', models.CharField(default='', max_length=1024)),
                ('cover_img', models.ImageField(blank=True, default=None, null=True, storage=backlogger.storage.OverwriteStorage(), upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomGameModel1',
        ),
    ]
