# Generated by Django 3.1.4 on 2020-12-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201230_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgamemodel',
            name='backlog_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_custom_game', serialize=False, to='app.backloggedgamesmodel'),
        ),
    ]
