# Generated by Django 3.1.4 on 2020-12-30 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20201230_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackloggedGamesModel',
            new_name='BackloggedGame',
        ),
        migrations.RenameModel(
            old_name='CustomGameModel',
            new_name='CustomGame',
        ),
        migrations.RenameModel(
            old_name='UserTimezoneModel',
            new_name='UserTimezone',
        ),
        migrations.RenameField(
            model_name='customgame',
            old_name='backlog_entry',
            new_name='backlogged',
        ),
    ]
