# Generated by Django 3.1.4 on 2020-12-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201230_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgame',
            name='game_id',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
    ]
