# Generated by Django 3.1.4 on 2020-12-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customgame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgame',
            name='game_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
