# Generated by Django 3.1.4 on 2020-12-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201230_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgame',
            name='game_id',
        ),
    ]
