# Generated by Django 3.1.4 on 2020-12-30 22:27

import backlogger.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_remove_customgame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggedgame',
            name='cover_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='backloggedgame',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='backloggedgame',
            name='game_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='backloggedgame',
            name='platform_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='customgame',
            name='cover_img',
            field=models.ImageField(storage=backlogger.storage.OverwriteStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='customgame',
            name='involved_companies',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='customgame',
            name='summary',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='customgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
